defaultMode = 5
fireSpeed = 50

# Available keys:
# leftclick, middleclick, rightclick, forward, backward, dpiloop, showdesktop,
# doubleclick, fire, off, dpiplus, dpiminus
[keymaps]
lmb = "leftclick"
scrollButton = "middleclick"
rmb = "rightclick"
forward = "forward"
backward = "backward"
plus = "dpiplus"
minus = "dpiminus"

[led]
time = 2 # only define if type is fixed or cyclic
type = "fixed" # Available modes: off, static, fixed, cyclic

[[modes]]
enabled = true
dpi = 200
color = "111"

[[modes]]
enabled = true
dpi = 600
color = "445"

[[modes]]
enabled = true
dpi = 1000
color = "CDF"

[[modes]]
enabled = true
dpi = 1600
color = "47F"

[[modes]]
enabled = true
dpi = 2400
color = "6E6"

[[modes]]
enabled = true
color = "F46"
dpi = 4800
